// <auto-generated />
namespace VixEng.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Remoção_de_campos_beneficios : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Remoção_de_campos_beneficios));
        
        string IMigrationMetadata.Id
        {
            get { return "201604131653565_Remoção_de_campos_beneficios"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
