// <auto-generated />
namespace VixEng.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Voltando_campoEmail_nao_Unico : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Voltando_campoEmail_nao_Unico));
        
        string IMigrationMetadata.Id
        {
            get { return "201604131927339_Voltando_campoEmail_nao_Unico"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
